Enhance AOAI / AI Studio Model Catalog Custom Skill
Azure-Samples/azure-search-power-skills pull request #216
Opened 2024-11-02 15:37 UTC by farzad528

## Purpose

### Changes Made
- [x] Refactored the custom skill endpoint to improve readability and maintainability.
- [x] Introduced a new `ScenarioType` Enum for better scenario management.
- [x] Added custom logging throughout the code to assist in debugging and monitoring.
- [x] Improved error handling using the `CustomSkillException` class for clearer error messaging.
- [x] Implemented a new method to load prompts from a JSON file, enhancing flexibility.
- [x] Introduced a health check endpoint to ensure service availability.
- [x] Added functionality to handle image data in the image captioning scenario with validation for base64 content.
- [x] Enhanced response formatting to accommodate different scenarios (summarization, entity recognition, image captioning).
- [x] Ensured compatibility with Azure's new chat completion client.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Get the code

```
git clone https://github.com/farzad528/azure-search-power-skills/tree/main
cd azure-search-vector-samples
git checkout main
deploy the new Functions 

```

* Test the code

```
# Replace with specific test commands or instructions as needed
```

## What to Check
Verify that the following are valid
* Ensure that the new custom skill functionality works correctly for all scenarios (summarization, entity recognition, image captioning).
* Confirm that error handling and logging are functioning as expected.

## Other Information

* This update ensures compatibility with the latest Azure chat completion client and improves the overall user experience.

2024-11-04 18:42 UTC, amitkalay commented
Hey @farzad528 - there are merge conflicts with this PR because of my recently merged changes. Can you please resolve those conflicts and resubmit this PR?

2024-11-05 17:18 UTC, amitkalay requested changes
looks good in general, but merge conflicts need to be resolved.

2024-11-05 18:56 UTC, farzad528 commented
@amitkalay I've overrided

2024-11-05 19:52 UTC, amitkalay approved these changes

2024-11-05 19:53 UTC, merged