Image Clustering Power Skill using DBSCAN
Azure-Samples/azure-search-power-skills pull request #51
Opened 2020-12-11 13:19 UTC by shanepeckham

## Purpose

* ...
This Power Skill will uses the [DBSCAN](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.dbscan.html)
unsupervised clustering algorithm alongside [VGG16](https://keras.io/api/applications/vgg/) to extract
visual features and cluster images. 

This skill is ideal for:

1) Exploring your data to identify clusters based on visual features during your data exploration phase
2) Using in conjunction with Custom Vision Classification to further cluster your images, for example if
you need a hierarchical classification structure.
3) Auto-labelling your images based on the clusters identified and the labels you associated with the clusters. Note
Azure Machine Learning has an auto-labelling feature already, this Power Skill should be used if this feature is not suitable
## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
The first step in the process is to extract VGG16 embeddings from the images and train the DBSCAN model on the extracted features.
To better understand the algorithm itself, please use explanatory notebook, it contains a local example of the process.
To leverage the power of Azure Machine Learning, train a model on a cluster and save trained model into registry to make it available for your custom skill, you can either use training notebook or proceed with setting up the full MLOps process using clustering pipeline.
As with any (especially, unsupervised) machine learning solution, inspecting the clusters generated and playing with the algorithm hyperparameters will be required.
To explore generated clusters and generate labels dictionary required for the custom skill, you can use labeling notebook. These labels are what will be indexed to retrieve the images.
Clusters report is also available under the registered model on the Azure Machine Learning Portal.
Deploy the skill and add the endpoint to your skillset file
Run your indexer [deployment/azuresearch/create_indexer.json]
Investigate your indexed data and compare the effect of using Image Clustering Power Skill and Computer Vision Service using Azure Search notebook.
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-01-21 00:41 UTC, vkurpad reviewed
I am in the process of deploying and testing the skill, will post any feedback if I run into issues.

2021-01-21 00:41 UTC, vkurpad commented on Vision/ImageClusteringSkill/README.md
> +This Power Skill will uses the [DBSCAN](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.dbscan.html)
Remove will

2021-01-21 00:41 UTC, vkurpad commented on Vision/ImageClusteringSkill/README.md
> +This skill is ideal for:
Could you add one visual example? A sample image that gets tagged

2021-01-21 00:41 UTC, vkurpad commented on Vision/ImageClusteringSkill/README.md
> +3) Deploy the skill and add the endpoint to your [skillset file](deployment/azuresearch/create_skillset.json)
No immediate action needed, but it would be good to convert the is step to use the AML skill in a future PR.

2021-02-02 01:02 UTC, bleroy requested changes
Thanks for the contribution. My general concern is that the signal to noise ratio is very small. There's a lot of boilerplate, plumbing, and sample files. It's hard for a newcomer to figure out where the relevant parts are and how to modify them to their needs. The weight of this change is also several times all the other skills in the repository combined.
I think in order to be more useful, it would be better to separate the actual skills and move the rest to optional zip files, documentation explaining how to build an deploy, etc.

2021-02-02 01:04 UTC, bleroy commented
There's also a few empty readme files that should be removed, and .DS_Store files should be excluded.

2021-02-05 09:45 UTC, shanepeckham commented on Vision/ImageClusteringSkill/ml/models/search_service.py
> +class SearchService:
This has now been removed

2021-02-05 09:49 UTC, shanepeckham commented on Template/PythonFastAPI/README.md
> +The infra folder contains terraform files to deploy this to FastAPI container to Web
Added

2021-02-05 11:09 UTC, closed without merging