Formsrec
Azure-Samples/azure-search-power-skills pull request #52
Opened 2020-12-18 06:49 UTC by vkurpad

## Purpose
Added the forms recognizer V2 skill with the invoice extraction and table extraction skills
* ...

## Does this introduce a breaking change?
No, but the AnalyzeForm skill is now deprecated
```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Deploy the AnalyzeFormV2 Skills and test the 3 new skills

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2020-12-18 19:12 UTC, bleroy commented
Thanks Vinod. First comment would be that I feel like we should find a way to better delineate the Python implementations from the C# ones across the repo. How do we want to structure our directories so users aren't confused? So that we can provide a Python and a C# implementation of the same skill?

2020-12-18 19:20 UTC, bleroy commented on Vision/AnalyzeFormV2/AnalyzeInvoice/__init__.py
> +
You have a few of those extra skipped lines across the PR. No big deal, but would be nice to fix.

2020-12-18 19:24 UTC, bleroy commented on Vision/AnalyzeFormV2/Readme.md
> +[![Deploy to Azure](https://azuredeploy.net/deploybutton.svg)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure-Samples%2Fazure-search-power-ski
This doesn't look right: it uses the "AnalyzeForm" dir instead of "AnalyzeFormV2", and you seem to be missing the file itself.

2020-12-18 19:24 UTC, bleroy commented on Vision/AnalyzeFormV2/Readme.md
> +azureDeploy: https://raw.githubusercontent.com/Azure-Samples/azure-search-power-skills/master/Vision/AnalyzeForm/azuredeploy.json
Wrong path

2020-12-18 19:30 UTC, bleroy requested changes
This looks great, thanks. There's just the small issues with the deployment file and the decision we need to make about Python+C# cohabitation, should be good to merge.

2021-02-01 23:19 UTC, bleroy requested changes

2021-02-01 23:19 UTC, bleroy commented on Vision/AnalyzeFormV2/AnalyzeForm/__init__.py
> +        formUrl = formUrl + formSasToken
Should there be some validation on those as well?

2021-02-01 23:19 UTC, bleroy commented on Vision/AnalyzeFormV2/AnalyzeForm/field-mappings.json
> +
Looks like this file should not exist (code refers to fieldmappings.json)

2021-02-01 23:19 UTC, bleroy commented on Vision/AnalyzeFormV2/AnalyzeInvoice/__init__.py
> +    return json.dumps(results, ensure_ascii=False, cls=DateTimeEncoder)
Should the boilerplate code be moved into some kind of utility class like we did in C#?

2021-02-01 23:19 UTC, bleroy commented on Vision/AnalyzeFormV2/Readme.md
> +# AnalyzeInvoice
Also add deployment buttons for each skill.

2021-02-01 23:21 UTC, bleroy commented
You should also add a link from the top-level readme file.

2021-02-04 19:34 UTC, vkurpad commented
> Thanks Vinod. First comment would be that I feel like we should find a way to better delineate the Python implementations from the C# ones across the repo. How do we want to structure our directories so users aren't confused? So that we can provide a Python and a C# implementation of the same skill?

Agreed! I see that as a challenge that is broader than just the language. There is a question of selective skill deployments as skills become more complex and expensive. I am spending some time on this....

2021-02-12 21:11 UTC, closed without merging