Fixed vision/AnalyzeForm GetFields and JSON struct
Azure-Samples/azure-search-power-skills pull request #54
Opened 2021-02-12 10:57 UTC by alpinedelight

## Purpose

* ...
The Vision/AnalyzeForm sample uses an outdated version of the form recogniser API which results in "unreferenced objects" exception errors in the GetFields function.
This has been raised in https://github.com/Azure-Samples/azure-search-power-skills/issues/31 back in July 2020.
The data model classes used do not reflect the actual API.

I've updated the data model and updated the LINQ (very simplistic) to point to new from recognizer API.

## Does this introduce a breaking change?

```
[ ] Yes
[❌ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[❌] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
Follow instructions per documentation: https://docs.microsoft.com/en-us/azure/search/cognitive-search-custom-skill-form
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-02-12 21:37 UTC, bleroy requested changes
Thanks for the contribution. Can you also remove the empty `__init__.py` file?

2021-02-12 21:37 UTC, bleroy commented on Vision/AnalyzeForm/AnalyzeForm.cs
> +                .Select(t => t.cells[0].Text);*/
Please remove commented code.

2021-02-12 21:37 UTC, bleroy commented on Vision/AnalyzeForm/AnalyzeForm.cs
> +                value = textValues[idx + 1];
Please collapse into ternary operator.

2022-02-28 22:59 UTC, bleroy commented
@alpinedelight, any update on this PR?

2022-08-11 17:02 UTC, bleroy commented
@alpinedelight any chance to get an updated PR?

2023-11-14 18:32 UTC, gmndrg commented
There were no changes made as requested to be able to merge and more than 1 year ago. Closing now. This can be reopened if needed.

2023-11-14 18:32 UTC, closed without merging