Text Summarizer with HuggingFace/Facebook BART model
Azure-Samples/azure-search-power-skills pull request #60
Opened 2021-03-19 16:11 UTC by shanepeckham

## Purpose

* This PR adds a PowerSkill to Summarize the text in a document and includes Azure Text Analytics NER

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Everything can be tested within the jupyter notebook section

## Other Information
Every step is documented in the README.md and jupyter notebook

2021-03-19 19:23 UTC, bleroy requested changes
Thanks for another great contrib!

2021-03-19 19:23 UTC, bleroy commented on Text/TextSummarization/README.md
> +   ```pythonn
```suggestion
   ```python
```

2021-03-19 19:23 UTC, bleroy commented on Text/TextSummarization/README.md
> +      python -m pip install -r requirements.txt
```suggestion
  python -m pip install -r requirements.txt
```

2021-03-19 19:23 UTC, bleroy commented on Text/TextSummarization/README.md
> +
```suggestion
```

2021-03-19 19:23 UTC, bleroy commented on Text/TextSummarization/README.md
> +    Downloading:   1%|███▉
```suggestion
    Downloading:   1%
```

2021-03-22 10:13 UTC, shanepeckham commented on Text/TextSummarization/README.md
> +![text summarization process](images/text_summarization_flow.png)
Added

2021-03-22 10:15 UTC, shanepeckham commented on Text/TextSummarization/README.md
> +
Removed

2021-03-22 10:15 UTC, shanepeckham commented on Text/TextSummarization/README.md
> +    Downloading:   1%|███▉
Changed

2021-03-27 02:10 UTC, merged